name: Tests

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
